Repository Cogno-IDU/smslibrary, pull requests merged in 2019-12, with the labels that each got.

#14 Implemented delivery report
  smslibrary/src/main/java/com/eis/smslibrary/SMSDeliveredBroadcastReceiver.java
  smslibrary/src/main/java/com/eis/smslibrary/SMSHandler.java
  smslibrary/src/main/java/com/eis/smslibrary/SMSMessage.java
  smslibrary/src/main/java/com/eis/smslibrary/SMSSentBroadcastReceiver.java
  smslibrary/src/main/java/com/eis/smslibrary/listeners/SMSDeliveredListener.java
Labels: enhancement

#16 Created README.md instructions
  README.md
Labels: documentation

#13 Feature: library working on app closed
  build.gradle
  smslibrary/build.gradle
  smslibrary/src/main/java/com/eis/smslibrary/SMSHandler.java
  smslibrary/src/main/java/com/eis/smslibrary/SMSReceivedBroadcastReceiver.java
  smslibrary/src/main/java/com/eis/smslibrary/listeners/SMSReceivedListener.java
  smslibrary/src/main/java/com/eis/smslibrary/listeners/SMSReceivedServiceListener.java
Labels: enhancement

#23 removed pleonastic o==null in Peer.equals()
  smslibrary/src/main/java/com/eis/smslibrary/SMSPeer.java
Labels: code strengthening

#26 Added Continuos Integration (CI) for Android
  .github/workflows/android.yml
  build.gradle
  gradlew
  smslibrary/src/test/java/com/eis/smslibrary/SMSPeerTest.java
Labels: code strengthening

#35 SMSManager Context and tests
  smslibrary/build.gradle
  smslibrary/src/main/java/com/eis/smslibrary/SMSCore.java
  smslibrary/src/main/java/com/eis/smslibrary/SMSManager.java
  smslibrary/src/test/java/com/eis/smslibrary/SMSHandlerTest.java
Labels: code strengthening

#37 Added pull request template
  .github/pull_request_template.md
Labels: feature request

#36 Universal SMSPeer
  README.md
  build.gradle
  smslibrary/build.gradle
  smslibrary/src/main/java/com/eis/smslibrary/SMSMessageHandler.java
  smslibrary/src/main/java/com/eis/smslibrary/SMSPeer.java
  smslibrary/src/main/java/com/eis/smslibrary/exceptions/InvalidTelephoneNumberException.java
  smslibrary/src/test/java/com/eis/smslibrary/SMSPeerTest.java
Labels: code strengthening
